# Generated by Django 5.2.9 on 2026-02-27 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'finanzas_category',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('boleta_servicios', 'Boleta de servicios'), ('boleta_exenta', 'Boleta exenta'), ('factura', 'Factura'), ('otro', 'Otro')], default='boleta_servicios', max_length=30)),
                ('folio', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='finanzas/invoices/')),
                ('enlace_sii', models.URLField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_facturas', to='database.organizacion')),
            ],
            options={
                'verbose_name': 'Boleta o factura',
                'verbose_name_plural': 'Boletas y facturas',
                'db_table': 'finanzas_invoice',
                'ordering': ['-fecha_emision', '-id'],
                'unique_together': {('organizacion', 'tipo', 'folio')},
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('num_clases', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_incluye_iva', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='database.organizacion')),
            ],
            options={
                'verbose_name': 'Plan de pago',
                'verbose_name_plural': 'Planes de pago',
                'db_table': 'finanzas_paymentplan',
                'ordering': ['organizacion__nombre', 'nombre'],
                'unique_together': {('organizacion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('monto_incluye_iva', models.BooleanField(default=False)),
                ('monto_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clases_asignadas', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.invoice')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_financieros', to='database.organizacion')),
                ('persona', models.ForeignKey(limit_choices_to={'roles__activo': True, 'roles__rol__codigo__iexact': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_financieros', to='database.persona')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.paymentplan')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'finanzas_payment',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='finanzas/transactions/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='finanzas.category')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_financieras', to='database.organizacion')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'finanzas_transaction',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clase_fecha', models.DateField()),
                ('estado', models.CharField(choices=[('consumido', 'Consumido'), ('pendiente', 'Pendiente'), ('deuda', 'Deuda')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_financiero', to='database.asistencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_asistencia', to='database.persona')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='finanzas.payment')),
            ],
            options={
                'verbose_name': 'Consumo de asistencia',
                'verbose_name_plural': 'Consumos de asistencia',
                'db_table': 'finanzas_attendanceconsumption',
                'ordering': ['-clase_fecha', '-id'],
                'indexes': [models.Index(fields=['persona', 'clase_fecha'], name='finanzas_at_persona_4a6041_idx'), models.Index(fields=['estado', 'clase_fecha'], name='finanzas_at_estado_041e5c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fecha_pago', 'organizacion'], name='finanzas_pa_fecha_p_b0cdef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['persona', 'fecha_pago'], name='finanzas_pa_persona_e11805_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fecha', 'organizacion'], name='finanzas_tr_fecha_071530_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tipo', 'fecha'], name='finanzas_tr_tipo_5d9434_idx'),
        ),
    ]
