# Generated by Django 5.2.9 on 2025-12-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('cuentas', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_profesores', to='organizaciones.organizacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='cuentas.persona')),
                ('sesiones', models.ManyToManyField(blank=True, related_name='liquidaciones', to='academia.sesionclase')),
            ],
            options={
                'verbose_name': 'Liquidacion profesor',
                'verbose_name_plural': 'Liquidaciones profesores',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TarifaPagoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_por_sesion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifas_profesores', to='academia.disciplina')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_profesores', to='organizaciones.organizacion')),
            ],
            options={
                'verbose_name': 'Tarifa pago profesor',
                'verbose_name_plural': 'Tarifas pago profesor',
                'ordering': ['organizacion', 'vigente_desde'],
            },
        ),
    ]
