# Generated by Django 5.2.9 on 2025-12-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionprofesor',
            name='monto_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liquidacionprofesor',
            name='monto_retencion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('afecta_iva', models.BooleanField(default=False)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.CharField(choices=[('talleres', 'Talleres/Clases'), ('arriendo', 'Arriendo'), ('insumos', 'Insumos'), ('honorarios', 'Honorarios'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=20)),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='organizaciones.organizacion')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
