# Generated by Django 5.2.9 on 2026-03-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0005_documentos_tributarios"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentotributario",
            unique_together={("organizacion", "tipo_documento", "folio", "rut_emisor")},
        ),
    ]
