# Generated by Django 5.2.9 on 2026-03-27

from django.db import migrations, models


def marcar_planes_por_defecto(apps, schema_editor):
    PaymentPlan = apps.get_model("finanzas", "PaymentPlan")
    for organizacion_id in PaymentPlan.objects.values_list("organizacion_id", flat=True).distinct():
        planes = PaymentPlan.objects.filter(organizacion_id=organizacion_id).order_by("id")
        primer_plan = planes.first()
        if not primer_plan:
            continue
        PaymentPlan.objects.filter(organizacion_id=organizacion_id).update(es_por_defecto=False)
        PaymentPlan.objects.filter(pk=primer_plan.pk).update(es_por_defecto=True)


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0006_documentotributario_unique_emisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="es_por_defecto",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(marcar_planes_por_defecto, migrations.RunPython.noop),
    ]
