# Generated by Django 5.2.9 on 2026-07-27 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_documentotributario_contraparte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='motivo_reversa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='revertido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='revertido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_revertidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
