# Generated by Django 5.2.9 on 2026-07-28 02:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_payment_motivo_reversa_payment_revertido_en_and_more'),
        ('personas', '0009_solicitudacceso_resolucion_organizacion_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePago',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave_idempotencia', models.CharField(max_length=128, unique=True)),
                ('cantidad_pagos', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('origen', models.CharField(default='pago_masivo', max_length=40)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pago', to='personas.organizacion')),
            ],
            options={
                'verbose_name': 'Lote de pagos',
                'verbose_name_plural': 'Lotes de pagos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.lotepago'),
        ),
    ]
