# Generated by Django 5.2.9 on 2026-08-10 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_alter_sesionclase_estado_liberacionsesion_and_more'),
        ('finanzas', '0011_lotepago_payment_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotepago',
            name='respaldo',
            field=models.FileField(blank=True, null=True, upload_to='finanzas/lotes/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='clave_idempotencia',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_operacionales', to='asistencias.disciplina'),
        ),
        migrations.AddField(
            model_name='payment',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_operacionales_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='respaldo',
            field=models.FileField(blank=True, null=True, upload_to='finanzas/pagos/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_operacional', to='finanzas.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_financieras_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
