# Generated by Django 5.2.9 on 2026-10-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_payment_clave_idempotencia_payment_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='documentos_tributarios',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='documento_tributario',
        ),
        migrations.DeleteModel(
            name='DocumentoTributario',
        ),
    ]
