"""
Django settings for plataformaelemental project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

"""
Legacy placeholder. The project now keeps its real settings inside the
``plataformaelemental.config`` package so this file intentionally stays empty.
"""
