# Generated by Django 5.2.9 on 2025-12-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50)),
                ('sitio_web', models.URLField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
