# Generated by Django 5.2.9 on 2026-06-01 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0005_organizacion_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=50)),
                ('dominio', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='personas.organizacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['dominio', 'modelo', 'objeto_id'], name='auditoria_a_dominio_8e747a_idx'), models.Index(fields=['organizacion', 'fecha'], name='auditoria_a_organiz_aaef91_idx'), models.Index(fields=['usuario', 'fecha'], name='auditoria_a_usuario_89b844_idx')],
            },
        ),
    ]
