# Generated by Django 5.2.9 on 2026-04-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('prefijo', models.CharField(editable=False, max_length=16, unique=True)),
                ('hash_clave', models.CharField(editable=False, max_length=64, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['nombre'],
            },
        ),
    ]
