# Generated by Django 5.2.9 on 2025-12-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cupo_mensual',
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pagos/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cuentas.persona'),
        ),
        migrations.AddField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cobros.suscripcion'),
        ),
        migrations.AddField(
            model_name='plan',
            name='clases_por_semana',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pago',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cobros.documentoventa'),
        ),
    ]
