# Generated by Django 5.2.9 on 2026-01-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_remove_sesionclase_profesor'),
        ('cobros', '0002_remove_plan_cupo_mensual_pago_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='academia.sesionclase'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('suscripcion', 'Suscripcion'), ('clase', 'Clase'), ('otro', 'Otro')], default='suscripcion', max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='monto_pactado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
