# Generated by Django 5.2.9 on 2026-01-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_pago_sesion_pago_tipo_suscripcion_descuento_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='clases_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='clases_usadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cobros.plan'),
        ),
        migrations.AddField(
            model_name='pago',
            name='valido_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='clases_por_mes',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('suscripcion', 'Plan'), ('plan', 'Plan'), ('clase', 'Clase'), ('otro', 'Otro')], default='suscripcion', max_length=20),
        ),
    ]
