# Generated by Django 5.2.9 on 2026-01-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0005_popular_clases_por_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('suscripcion', 'Plan'), ('plan', 'Plan'), ('clase', 'Clase'), ('otro', 'Otro')], default='plan', max_length=20),
        ),
    ]
