# Generated by Django 5.2.9 on 2026-01-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0006_alter_pago_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('plan', 'Plan'), ('clase', 'Clase'), ('otro', 'Otro')], default='plan', max_length=20),
        ),
    ]
