# Generated by Django 5.2.9 on 2026-01-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_remove_asistencia_suscripcion'),
        ('cobros', '0008_migrar_tipo_suscripcion_a_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='suscripcion',
        ),
        migrations.RemoveField(
            model_name='documentoventa',
            name='suscripcion',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
