# Generated by Django 5.2.9 on 2026-02-16 17:11

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_pago_cycle_fields(apps, schema_editor):
    Pago = apps.get_model("cobros", "Pago")
    for pago in Pago.objects.all().iterator():
        if not pago.paid_at:
            pago.paid_at = django.utils.timezone.now()
        if not pago.ciclo_start:
            pago.ciclo_start = pago.paid_at
        if not pago.ciclo_end and pago.ciclo_start:
            pago.ciclo_end = pago.ciclo_start + timedelta(days=30)
        if not pago.precio_lista_referencia and pago.plan_id:
            pago.precio_lista_referencia = pago.plan.precio
        if not pago.precio_lista_referencia and pago.tipo == "clase":
            pago.precio_lista_referencia = 9000
        if not pago.valido_hasta and pago.ciclo_end:
            pago.valido_hasta = pago.ciclo_end.date()
        pago.save(
            update_fields=[
                "paid_at",
                "ciclo_start",
                "ciclo_end",
                "precio_lista_referencia",
                "valido_hasta",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0009_remove_pago_suscripcion_and_more'),
        ('cuentas', '0003_alter_persona_email'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='carryover_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='ciclo_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='ciclo_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='freeze_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pago',
            name='precio_lista_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarifa_clase_personalizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CondicionCobroPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('clase_especial', 'Clase especial'), ('beca', 'Beca')], default='normal', max_length=20)),
                ('tarifa_clase_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_cobro_persona', to='organizaciones.organizacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_cobro', to='cuentas.persona')),
            ],
            options={
                'verbose_name': 'Condicion de cobro persona',
                'verbose_name_plural': 'Condiciones de cobro persona',
                'ordering': ['-vigente_desde', '-id'],
            },
        ),
        migrations.RunPython(backfill_pago_cycle_fields, migrations.RunPython.noop),
    ]
