# Generated by Django 5.2.9 on 2026-04-29 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0004_personarol_retencion_sii'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_segundos', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('frecuencia_minutos', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('seguir_redirecciones', models.BooleanField(default=True)),
                ('user_agent', models.CharField(default='Plataforma Elemental Monitor/1.0', max_length=200)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de monitor',
                'verbose_name_plural': 'Configuracion de monitor',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_proyectos', to='personas.organizacion')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('dominio', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('advertencia', 'Advertencia'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('ultimo_check_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='monitor.proyecto')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url_final', models.URLField(blank=True, max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('ssl_valido', models.BooleanField(blank=True, null=True)),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='monitor.sitio')),
            ],
            options={
                'verbose_name': 'Discovery de sitio',
                'verbose_name_plural': 'Discoveries de sitio',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_segundos', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('frecuencia_minutos', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('seguir_redirecciones', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='monitor.sitio')),
            ],
            options={
                'verbose_name': 'Configuracion de sitio',
                'verbose_name_plural': 'Configuraciones de sitio',
            },
        ),
        migrations.AddConstraint(
            model_name='sitio',
            constraint=models.UniqueConstraint(fields=('proyecto', 'url'), name='monitor_sitio_unico_por_proyecto_url'),
        ),
    ]
