# Generated by Django 5.2.9 on 2026-01-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        ('cuentas', '0003_alter_persona_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionclase',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='sesiones_en_equipo', to='cuentas.persona'),
        ),
        migrations.AlterField(
            model_name='sesionclase',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
