# Generated by Django 5.2.9 on 2026-02-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='es_exenta_iva',
            field=models.BooleanField(default=False, help_text='Marcar si la organizacion aplica exencion de IVA (Ley 21.622).'),
        ),
    ]
