BEGIN;
-- AlterField SesionClase.estado: no-op en PostgreSQL para este estado previo.
CREATE TABLE "asistencias_liberacionsesion" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "motivo" text NOT NULL,
  "liberada_en" timestamp with time zone NOT NULL,
  "liberada_por_id" integer NOT NULL,
  "sesion_id" bigint NOT NULL UNIQUE
);
CREATE TABLE "asistencias_alumnodisciplina" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "activa" boolean NOT NULL,
  "origen" varchar(20) NOT NULL,
  "asignada_en" timestamp with time zone NOT NULL,
  "revisada_en" timestamp with time zone NULL,
  "alumno_id" bigint NOT NULL,
  "asignada_por_id" integer NULL,
  "disciplina_id" bigint NOT NULL,
  "revisada_por_id" integer NULL,
  CONSTRAINT "asistencias_alumno_disciplina_unico" UNIQUE ("disciplina_id", "alumno_id")
);
CREATE TABLE "asistencias_asignacionprofesordisciplina" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "activa" boolean NOT NULL,
  "origen" varchar(20) NOT NULL,
  "asignada_en" timestamp with time zone NOT NULL,
  "revisada_en" timestamp with time zone NULL,
  "asignada_por_id" integer NULL,
  "disciplina_id" bigint NOT NULL,
  "profesor_id" bigint NOT NULL,
  "revisada_por_id" integer NULL,
  CONSTRAINT "asistencias_profesor_disciplina_unica" UNIQUE ("disciplina_id", "profesor_id")
);
-- RunPython migrar_asignaciones_historicas no puede representarse como SQL.
ALTER TABLE "asistencias_liberacionsesion" ADD CONSTRAINT "asistencias_liberaci_liberada_por_id_e863e225_fk_auth_user" FOREIGN KEY ("liberada_por_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_liberacionsesion" ADD CONSTRAINT "asistencias_liberaci_sesion_id_9518cbad_fk_academia_" FOREIGN KEY ("sesion_id") REFERENCES "academia_sesionclase" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "asistencias_liberacionsesion_liberada_por_id_e863e225" ON "asistencias_liberacionsesion" ("liberada_por_id");
ALTER TABLE "asistencias_alumnodisciplina" ADD CONSTRAINT "asistencias_alumnodi_alumno_id_e080d86c_fk_cuentas_p" FOREIGN KEY ("alumno_id") REFERENCES "cuentas_persona" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_alumnodisciplina" ADD CONSTRAINT "asistencias_alumnodi_asignada_por_id_5681baf7_fk_auth_user" FOREIGN KEY ("asignada_por_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_alumnodisciplina" ADD CONSTRAINT "asistencias_alumnodi_disciplina_id_4176f2ea_fk_academia_" FOREIGN KEY ("disciplina_id") REFERENCES "academia_disciplina" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_alumnodisciplina" ADD CONSTRAINT "asistencias_alumnodi_revisada_por_id_9ca6117e_fk_auth_user" FOREIGN KEY ("revisada_por_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "asistencias_alumnodisciplina_alumno_id_e080d86c" ON "asistencias_alumnodisciplina" ("alumno_id");
CREATE INDEX "asistencias_alumnodisciplina_asignada_por_id_5681baf7" ON "asistencias_alumnodisciplina" ("asignada_por_id");
CREATE INDEX "asistencias_alumnodisciplina_disciplina_id_4176f2ea" ON "asistencias_alumnodisciplina" ("disciplina_id");
CREATE INDEX "asistencias_alumnodisciplina_revisada_por_id_9ca6117e" ON "asistencias_alumnodisciplina" ("revisada_por_id");
ALTER TABLE "asistencias_asignacionprofesordisciplina" ADD CONSTRAINT "asistencias_asignaci_asignada_por_id_ddfa7e5f_fk_auth_user" FOREIGN KEY ("asignada_por_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_asignacionprofesordisciplina" ADD CONSTRAINT "asistencias_asignaci_disciplina_id_b05a41f8_fk_academia_" FOREIGN KEY ("disciplina_id") REFERENCES "academia_disciplina" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_asignacionprofesordisciplina" ADD CONSTRAINT "asistencias_asignaci_profesor_id_3aafbe7d_fk_cuentas_p" FOREIGN KEY ("profesor_id") REFERENCES "cuentas_persona" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "asistencias_asignacionprofesordisciplina" ADD CONSTRAINT "asistencias_asignaci_revisada_por_id_c7549ad0_fk_auth_user" FOREIGN KEY ("revisada_por_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "asistencias_asignacionprof_asignada_por_id_ddfa7e5f" ON "asistencias_asignacionprofesordisciplina" ("asignada_por_id");
CREATE INDEX "asistencias_asignacionprofesordisciplina_disciplina_id_b05a41f8" ON "asistencias_asignacionprofesordisciplina" ("disciplina_id");
CREATE INDEX "asistencias_asignacionprofesordisciplina_profesor_id_3aafbe7d" ON "asistencias_asignacionprofesordisciplina" ("profesor_id");
CREATE INDEX "asistencias_asignacionprof_revisada_por_id_c7549ad0" ON "asistencias_asignacionprofesordisciplina" ("revisada_por_id");
COMMIT;
