from django.urls import path

from . import views

app_name = "webapp"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("notificaciones/", views.notificaciones, name="notificaciones"),
    path("ayuda/", views.ayuda, name="ayuda"),
    path("disciplinas/", views.disciplinas_list, name="disciplinas_list"),
    path("disciplinas/nueva/", views.disciplina_create, name="disciplina_create"),
    path("disciplinas/<int:pk>/editar/", views.disciplina_edit, name="disciplina_edit"),
    path("horarios/", views.horarios, name="horarios"),
    path("sesiones/", views.sesiones_list, name="sesiones_list"),
    path("sesiones/nueva/", views.sesion_create, name="sesion_create"),
    path("sesiones/<int:pk>/", views.sesion_detail, name="sesion_detail"),
    path("sesiones/<int:pk>/asistencia/", views.sesion_asistencia, name="sesion_asistencia"),
    path("asistencia/", views.asistencia_hoy, name="asistencia_hoy"),
    path("asistencia/historial/", views.asistencia_historial, name="asistencia_historial"),
    path("personas/", views.personas_list, name="personas_list"),
    path("personas/nueva/", views.persona_create, name="persona_create"),
    path("personas/<int:pk>/", views.persona_detail, name="persona_detail"),
    path("personas/<int:pk>/roles/", views.persona_roles, name="persona_roles"),
    path("personas/<int:pk>/usuario/", views.persona_usuario, name="persona_usuario"),
    path("planes/", views.planes_list, name="planes_list"),
    path("estudiantes/", views.estudiantes_list, name="estudiantes_list"),
    path("estudiantes/<int:pk>/estado/", views.estudiante_estado, name="estudiante_estado"),
    path("estudiantes/<int:pk>/suscripciones/", views.estudiante_suscripciones, name="estudiante_suscripciones"),
    path("convenios/", views.convenios_list, name="convenios_list"),
    path("pagos/", views.pagos_list, name="pagos_list"),
    path("pagos/nuevo/", views.pago_create, name="pago_create"),
    path("pagos/<int:pk>/", views.pago_detail, name="pago_detail"),
    path("morosos/", views.morosos_list, name="morosos_list"),
    path("liquidaciones/", views.liquidaciones_list, name="liquidaciones_list"),
    path("liquidaciones/nueva/", views.liquidacion_create, name="liquidacion_create"),
    path("liquidaciones/<int:pk>/", views.liquidacion_detail, name="liquidacion_detail"),
    path("finanzas/", views.finanzas_dashboard, name="finanzas_dashboard"),
    path("finanzas/movimientos/", views.movimientos_list, name="movimientos_list"),
    path("finanzas/movimientos/nuevo/", views.movimiento_create, name="movimiento_create"),
    path("finanzas/resumen/", views.finanzas_resumen, name="finanzas_resumen"),
    path("finanzas/categorias/", views.finanzas_categorias, name="finanzas_categorias"),
    path("reportes/", views.reportes_dashboard, name="reportes_dashboard"),
    path("reportes/exportar/", views.reportes_exportar, name="reportes_exportar"),
    path("importaciones/", views.importaciones_dashboard, name="importaciones_dashboard"),
    path("importaciones/historial/", views.importaciones_historial, name="importaciones_historial"),
    path("configuracion/", views.configuracion, name="configuracion"),
    path("usuarios/", views.usuarios_list, name="usuarios_list"),
    path("auditoria/", views.auditoria_log, name="auditoria_log"),
]
