# Generated by Django 5.2.9 on 2025-12-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='cobros.conveniointercambio'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='cobros.suscripcion'),
        ),
    ]
