# Generated by Django 5.2.9 on 2026-01-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_asistencia_convenio_asistencia_suscripcion'),
        ('cobros', '0004_pago_clases_total_pago_clases_usadas_pago_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='pago_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_plan', to='cobros.pago'),
        ),
    ]
