# Generated by Django 5.2.9 on 2026-07-27 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_disciplina_badge_color'),
        ('personas', '0009_solicitudacceso_resolucion_organizacion_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseLiberada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('liberada_en', models.DateTimeField(auto_now_add=True)),
                ('revertida_en', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clase_liberada', to='asistencias.asistencia')),
                ('liberada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_liberadas_registradas', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_liberadas', to='personas.organizacion')),
                ('revertida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_liberadas_revertidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase liberada',
                'verbose_name_plural': 'Clases liberadas',
                'db_table': 'asistencias_claseliberada',
            },
        ),
    ]
