# Generated by Django 5.2.9 on 2026-08-10 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_asignaciones_historicas(apps, schema_editor):
    SesionClase = apps.get_model("asistencias", "SesionClase")
    Asistencia = apps.get_model("asistencias", "Asistencia")
    AsignacionProfesorDisciplina = apps.get_model("asistencias", "AsignacionProfesorDisciplina")
    AlumnoDisciplina = apps.get_model("asistencias", "AlumnoDisciplina")

    asignaciones_profesor = (
        SesionClase.profesores.through.objects.values_list(
            "sesionclase__disciplina_id",
            "persona_id",
        )
        .distinct()
        .iterator(chunk_size=2000)
    )
    lote = []
    for disciplina_id, profesor_id in asignaciones_profesor:
        lote.append(
            AsignacionProfesorDisciplina(
                disciplina_id=disciplina_id,
                profesor_id=profesor_id,
                activa=False,
                origen="historica",
            )
        )
        if len(lote) == 2000:
            AsignacionProfesorDisciplina.objects.bulk_create(lote, ignore_conflicts=True)
            lote = []
    if lote:
        AsignacionProfesorDisciplina.objects.bulk_create(lote, ignore_conflicts=True)

    asignaciones_alumno = (
        Asistencia.objects.values_list("sesion__disciplina_id", "persona_id")
        .distinct()
        .iterator(chunk_size=2000)
    )
    lote = []
    for disciplina_id, alumno_id in asignaciones_alumno:
        lote.append(
            AlumnoDisciplina(
                disciplina_id=disciplina_id,
                alumno_id=alumno_id,
                activa=False,
                origen="historica",
            )
        )
        if len(lote) == 2000:
            AlumnoDisciplina.objects.bulk_create(lote, ignore_conflicts=True)
            lote = []
    if lote:
        AlumnoDisciplina.objects.bulk_create(lote, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_claseliberada'),
        ('personas', '0009_solicitudacceso_resolucion_organizacion_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionclase',
            name='estado',
            field=models.CharField(choices=[('programada', 'Planificada'), ('abierta', 'Abierta'), ('completada', 'Cerrada'), ('cancelada', 'Cancelada')], default='programada', max_length=20),
        ),
        migrations.CreateModel(
            name='LiberacionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('liberada_en', models.DateTimeField(auto_now_add=True)),
                ('liberada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_liberadas', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liberacion_operativa', to='asistencias.sesionclase')),
            ],
            options={
                'verbose_name': 'Liberación de sesión',
                'verbose_name_plural': 'Liberaciones de sesiones',
                'db_table': 'asistencias_liberacionsesion',
            },
        ),
        migrations.CreateModel(
            name='AlumnoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('explicita', 'Explícita'), ('historica', 'Inferida desde historia')], default='explicita', max_length=20)),
                ('asignada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_asignadas', to='personas.persona')),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_alumno_disciplina_creadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_asignados', to='asistencias.disciplina')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_alumno_disciplina_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno de disciplina',
                'verbose_name_plural': 'Alumnos de disciplinas',
                'db_table': 'asistencias_alumnodisciplina',
                'constraints': [models.UniqueConstraint(fields=('disciplina', 'alumno'), name='asistencias_alumno_disciplina_unico')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionProfesorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('explicita', 'Explícita'), ('historica', 'Inferida desde historia')], default='explicita', max_length=20)),
                ('asignada_en', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_profesor_disciplina_creadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_profesores', to='asistencias.disciplina')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_disciplinas', to='personas.persona')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_profesor_disciplina_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de profesor a disciplina',
                'verbose_name_plural': 'Asignaciones de profesores a disciplinas',
                'db_table': 'asistencias_asignacionprofesordisciplina',
                'constraints': [models.UniqueConstraint(fields=('disciplina', 'profesor'), name='asistencias_profesor_disciplina_unica')],
            },
        ),
        migrations.RunPython(migrar_asignaciones_historicas, migrations.RunPython.noop),
    ]
