# Generated by Django 5.2.9 on 2026-01-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_asistencia_pago_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='suscripcion',
        ),
    ]
