# Generated by Django 5.2.9 on 2026-02-16 17:11

from django.db import migrations, models


def backfill_estado_cobro(apps, schema_editor):
    Asistencia = apps.get_model("asistencias", "Asistencia")
    Asistencia.objects.filter(pago_plan__isnull=False).update(
        estado_cobro="cubierta",
        modalidad_cobro="plan",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_remove_asistencia_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado_cobro',
            field=models.CharField(choices=[('cubierta', 'Cubierta'), ('deuda', 'Deuda')], default='deuda', max_length=20),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='factor_pago_profesor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='modalidad_cobro',
            field=models.CharField(choices=[('plan', 'Plan'), ('clase_normal', 'Clase normal'), ('clase_especial', 'Clase especial'), ('beca', 'Beca')], default='clase_normal', max_length=30),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='monto_cobro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_estado_cobro, migrations.RunPython.noop),
    ]
