# Generated by Django 5.2.9 on 2026-06-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_personarol_retencion_sii'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizaciones/logos/'),
        ),
    ]
